// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `connect_tcp`, `exchange_initiator`, `finish_ok`, `pair_noise`, `pair_with_psk`, `read_frame`, `seal_checked`, `stretch_into`, `write_frame`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `PairInput`

KeypairOut bridgeGenKeypair() =>
    RustLib.instance.api.crateApiBridgeGenKeypair();

QrOut bridgeQrDecode({required String qrText, required BigInt nowUnix}) =>
    RustLib.instance.api.crateApiBridgeQrDecode(
      qrText: qrText,
      nowUnix: nowUnix,
    );

Uint8List bridgeSealMove({
  required List<int> key,
  required BigInt session,
  required BigInt seq,
  required int dx,
  required int dy,
}) => RustLib.instance.api.crateApiBridgeSealMove(
  key: key,
  session: session,
  seq: seq,
  dx: dx,
  dy: dy,
);

Uint8List bridgeSealClick({
  required List<int> key,
  required BigInt session,
  required BigInt seq,
  required int button,
}) => RustLib.instance.api.crateApiBridgeSealClick(
  key: key,
  session: session,
  seq: seq,
  button: button,
);

Uint8List bridgeSealScroll({
  required List<int> key,
  required BigInt session,
  required BigInt seq,
  required int dx,
  required int dy,
}) => RustLib.instance.api.crateApiBridgeSealScroll(
  key: key,
  session: session,
  seq: seq,
  dx: dx,
  dy: dy,
);

Uint8List bridgeSealButton({
  required List<int> key,
  required BigInt session,
  required BigInt seq,
  required int button,
  required bool down,
}) => RustLib.instance.api.crateApiBridgeSealButton(
  key: key,
  session: session,
  seq: seq,
  button: button,
  down: down,
);

Uint8List bridgeSealPing({
  required List<int> key,
  required BigInt session,
  required BigInt seq,
  required BigInt timestampMs,
}) => RustLib.instance.api.crateApiBridgeSealPing(
  key: key,
  session: session,
  seq: seq,
  timestampMs: timestampMs,
);

OpenOut bridgeOpen({required List<int> key, required List<int> packet}) =>
    RustLib.instance.api.crateApiBridgeOpen(key: key, packet: packet);

/// Stub kept for the Phase 0/1 API shape; prefer the FRB functions above.
Future<String> bridgeHello() => RustLib.instance.api.crateApiBridgeHello();

/// Blocking QR ceremony: TCP + Noise XXpsk3 + fingerprint check, then wait
/// for the desktop approval (server closes on deny/timeout). Returns session
/// keys on `OK`. `client_priv` is this phone's long-term static key —
/// generate once via [`bridge_gen_keypair`], keep in secure storage, and
/// reuse for every pairing and reconnect. Runs on FRB's blocking pool;
/// also bound it on the Dart side.
PairOut bridgePairQr({
  required String qrText,
  required String tcpHost,
  required String deviceName,
  required List<int> clientPriv,
}) => RustLib.instance.api.crateApiBridgePairQr(
  qrText: qrText,
  tcpHost: tcpHost,
  deviceName: deviceName,
  clientPriv: clientPriv,
);

/// Blocking short-code ceremony: SPAKE2 first, then the same Noise
/// handshake keyed by the SPAKE2 output.
PairOut bridgePairCode({
  required String host,
  required int tcpPort,
  required String code,
  required List<int> serverFp,
  required String serverName,
  required String deviceName,
  required List<int> clientPriv,
}) => RustLib.instance.api.crateApiBridgePairCode(
  host: host,
  tcpPort: tcpPort,
  code: code,
  serverFp: serverFp,
  serverName: serverName,
  deviceName: deviceName,
  clientPriv: clientPriv,
);

/// Blocking reconnect with the stored keypair. No approval, no ceremony.
PairOut bridgeReconnect({
  required String host,
  required int tcpPort,
  required List<int> clientPriv,
  required List<int> serverFp,
  required String serverName,
  required String deviceName,
}) => RustLib.instance.api.crateApiBridgeReconnect(
  host: host,
  tcpPort: tcpPort,
  clientPriv: clientPriv,
  serverFp: serverFp,
  serverName: serverName,
  deviceName: deviceName,
);

/// Fresh Noise static keypair for this phone.
class KeypairOut {
  final Uint8List privateKey;
  final Uint8List publicKey;

  const KeypairOut({required this.privateKey, required this.publicKey});

  @override
  int get hashCode => privateKey.hashCode ^ publicKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeypairOut &&
          runtimeType == other.runtimeType &&
          privateKey == other.privateKey &&
          publicKey == other.publicKey;
}

/// Opened packet for the phone (PONG handling, control acks).
class OpenOut {
  final bool ok;
  final String error;
  final BigInt session;
  final BigInt seq;
  final int msgType;

  /// MOVE/SCROLL: dx. CLICK/DOWN/UP: button. PING/PONG: low 32 bits of ts.
  final PlatformInt64 a;

  /// MOVE/SCROLL: dy. PING/PONG: high 32 bits of ts.
  final PlatformInt64 b;

  const OpenOut({
    required this.ok,
    required this.error,
    required this.session,
    required this.seq,
    required this.msgType,
    required this.a,
    required this.b,
  });

  @override
  int get hashCode =>
      ok.hashCode ^
      error.hashCode ^
      session.hashCode ^
      seq.hashCode ^
      msgType.hashCode ^
      a.hashCode ^
      b.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OpenOut &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          error == other.error &&
          session == other.session &&
          seq == other.seq &&
          msgType == other.msgType &&
          a == other.a &&
          b == other.b;
}

/// Output of a pairing/reconnect attempt.
class PairOut {
  final bool ok;
  final String error;
  final Uint8List phoneKey;
  final Uint8List desktopKey;
  final int udpPort;
  final BigInt sessionHint;
  final String serverName;

  const PairOut({
    required this.ok,
    required this.error,
    required this.phoneKey,
    required this.desktopKey,
    required this.udpPort,
    required this.sessionHint,
    required this.serverName,
  });

  @override
  int get hashCode =>
      ok.hashCode ^
      error.hashCode ^
      phoneKey.hashCode ^
      desktopKey.hashCode ^
      udpPort.hashCode ^
      sessionHint.hashCode ^
      serverName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PairOut &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          error == other.error &&
          phoneKey == other.phoneKey &&
          desktopKey == other.desktopKey &&
          udpPort == other.udpPort &&
          sessionHint == other.sessionHint &&
          serverName == other.serverName;
}

/// Decoded QR for the phone UI (pre-validated, expiry-checked).
class QrOut {
  final bool ok;
  final String error;
  final String host;
  final int tcpPort;
  final int udpPort;
  final Uint8List serverFp;
  final String deviceName;

  const QrOut({
    required this.ok,
    required this.error,
    required this.host,
    required this.tcpPort,
    required this.udpPort,
    required this.serverFp,
    required this.deviceName,
  });

  @override
  int get hashCode =>
      ok.hashCode ^
      error.hashCode ^
      host.hashCode ^
      tcpPort.hashCode ^
      udpPort.hashCode ^
      serverFp.hashCode ^
      deviceName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QrOut &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          error == other.error &&
          host == other.host &&
          tcpPort == other.tcpPort &&
          udpPort == other.udpPort &&
          serverFp == other.serverFp &&
          deviceName == other.deviceName;
}
