// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -538135717;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'trackpad_bridge',
        ioDirectory: '../../crates/trackpad-bridge/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  KeypairOut crateApiBridgeGenKeypair();

  Future<String> crateApiBridgeHello();

  OpenOut crateApiBridgeOpen({
    required List<int> key,
    required List<int> packet,
  });

  PairOut crateApiBridgePairCode({
    required String host,
    required int tcpPort,
    required String code,
    required List<int> serverFp,
    required String serverName,
    required String deviceName,
    required List<int> clientPriv,
  });

  PairOut crateApiBridgePairQr({
    required String qrText,
    required String tcpHost,
    required String deviceName,
    required List<int> clientPriv,
  });

  QrOut crateApiBridgeQrDecode({
    required String qrText,
    required BigInt nowUnix,
  });

  PairOut crateApiBridgeReconnect({
    required String host,
    required int tcpPort,
    required List<int> clientPriv,
    required List<int> serverFp,
    required String serverName,
    required String deviceName,
  });

  Uint8List crateApiBridgeSealButton({
    required List<int> key,
    required BigInt session,
    required BigInt seq,
    required int button,
    required bool down,
  });

  Uint8List crateApiBridgeSealClick({
    required List<int> key,
    required BigInt session,
    required BigInt seq,
    required int button,
  });

  Uint8List crateApiBridgeSealMove({
    required List<int> key,
    required BigInt session,
    required BigInt seq,
    required int dx,
    required int dy,
  });

  Uint8List crateApiBridgeSealPing({
    required List<int> key,
    required BigInt session,
    required BigInt seq,
    required BigInt timestampMs,
  });

  Uint8List crateApiBridgeSealScroll({
    required List<int> key,
    required BigInt session,
    required BigInt seq,
    required int dx,
    required int dy,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  KeypairOut crateApiBridgeGenKeypair() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_keypair_out,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBridgeGenKeypairConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeGenKeypairConstMeta =>
      const TaskConstMeta(debugName: "bridge_gen_keypair", argNames: []);

  @override
  Future<String> crateApiBridgeHello() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBridgeHelloConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeHelloConstMeta =>
      const TaskConstMeta(debugName: "bridge_hello", argNames: []);

  @override
  OpenOut crateApiBridgeOpen({
    required List<int> key,
    required List<int> packet,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(key, serializer);
          sse_encode_list_prim_u_8_loose(packet, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_open_out,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBridgeOpenConstMeta,
        argValues: [key, packet],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeOpenConstMeta => const TaskConstMeta(
    debugName: "bridge_open",
    argNames: ["key", "packet"],
  );

  @override
  PairOut crateApiBridgePairCode({
    required String host,
    required int tcpPort,
    required String code,
    required List<int> serverFp,
    required String serverName,
    required String deviceName,
    required List<int> clientPriv,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(host, serializer);
          sse_encode_u_16(tcpPort, serializer);
          sse_encode_String(code, serializer);
          sse_encode_list_prim_u_8_loose(serverFp, serializer);
          sse_encode_String(serverName, serializer);
          sse_encode_String(deviceName, serializer);
          sse_encode_list_prim_u_8_loose(clientPriv, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_pair_out,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBridgePairCodeConstMeta,
        argValues: [
          host,
          tcpPort,
          code,
          serverFp,
          serverName,
          deviceName,
          clientPriv,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgePairCodeConstMeta => const TaskConstMeta(
    debugName: "bridge_pair_code",
    argNames: [
      "host",
      "tcpPort",
      "code",
      "serverFp",
      "serverName",
      "deviceName",
      "clientPriv",
    ],
  );

  @override
  PairOut crateApiBridgePairQr({
    required String qrText,
    required String tcpHost,
    required String deviceName,
    required List<int> clientPriv,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(qrText, serializer);
          sse_encode_String(tcpHost, serializer);
          sse_encode_String(deviceName, serializer);
          sse_encode_list_prim_u_8_loose(clientPriv, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_pair_out,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBridgePairQrConstMeta,
        argValues: [qrText, tcpHost, deviceName, clientPriv],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgePairQrConstMeta => const TaskConstMeta(
    debugName: "bridge_pair_qr",
    argNames: ["qrText", "tcpHost", "deviceName", "clientPriv"],
  );

  @override
  QrOut crateApiBridgeQrDecode({
    required String qrText,
    required BigInt nowUnix,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(qrText, serializer);
          sse_encode_u_64(nowUnix, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_qr_out,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBridgeQrDecodeConstMeta,
        argValues: [qrText, nowUnix],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeQrDecodeConstMeta => const TaskConstMeta(
    debugName: "bridge_qr_decode",
    argNames: ["qrText", "nowUnix"],
  );

  @override
  PairOut crateApiBridgeReconnect({
    required String host,
    required int tcpPort,
    required List<int> clientPriv,
    required List<int> serverFp,
    required String serverName,
    required String deviceName,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(host, serializer);
          sse_encode_u_16(tcpPort, serializer);
          sse_encode_list_prim_u_8_loose(clientPriv, serializer);
          sse_encode_list_prim_u_8_loose(serverFp, serializer);
          sse_encode_String(serverName, serializer);
          sse_encode_String(deviceName, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_pair_out,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBridgeReconnectConstMeta,
        argValues: [
          host,
          tcpPort,
          clientPriv,
          serverFp,
          serverName,
          deviceName,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeReconnectConstMeta => const TaskConstMeta(
    debugName: "bridge_reconnect",
    argNames: [
      "host",
      "tcpPort",
      "clientPriv",
      "serverFp",
      "serverName",
      "deviceName",
    ],
  );

  @override
  Uint8List crateApiBridgeSealButton({
    required List<int> key,
    required BigInt session,
    required BigInt seq,
    required int button,
    required bool down,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(key, serializer);
          sse_encode_u_64(session, serializer);
          sse_encode_u_64(seq, serializer);
          sse_encode_u_8(button, serializer);
          sse_encode_bool(down, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBridgeSealButtonConstMeta,
        argValues: [key, session, seq, button, down],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeSealButtonConstMeta => const TaskConstMeta(
    debugName: "bridge_seal_button",
    argNames: ["key", "session", "seq", "button", "down"],
  );

  @override
  Uint8List crateApiBridgeSealClick({
    required List<int> key,
    required BigInt session,
    required BigInt seq,
    required int button,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(key, serializer);
          sse_encode_u_64(session, serializer);
          sse_encode_u_64(seq, serializer);
          sse_encode_u_8(button, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBridgeSealClickConstMeta,
        argValues: [key, session, seq, button],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeSealClickConstMeta => const TaskConstMeta(
    debugName: "bridge_seal_click",
    argNames: ["key", "session", "seq", "button"],
  );

  @override
  Uint8List crateApiBridgeSealMove({
    required List<int> key,
    required BigInt session,
    required BigInt seq,
    required int dx,
    required int dy,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(key, serializer);
          sse_encode_u_64(session, serializer);
          sse_encode_u_64(seq, serializer);
          sse_encode_i_32(dx, serializer);
          sse_encode_i_32(dy, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBridgeSealMoveConstMeta,
        argValues: [key, session, seq, dx, dy],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeSealMoveConstMeta => const TaskConstMeta(
    debugName: "bridge_seal_move",
    argNames: ["key", "session", "seq", "dx", "dy"],
  );

  @override
  Uint8List crateApiBridgeSealPing({
    required List<int> key,
    required BigInt session,
    required BigInt seq,
    required BigInt timestampMs,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(key, serializer);
          sse_encode_u_64(session, serializer);
          sse_encode_u_64(seq, serializer);
          sse_encode_u_64(timestampMs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBridgeSealPingConstMeta,
        argValues: [key, session, seq, timestampMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeSealPingConstMeta => const TaskConstMeta(
    debugName: "bridge_seal_ping",
    argNames: ["key", "session", "seq", "timestampMs"],
  );

  @override
  Uint8List crateApiBridgeSealScroll({
    required List<int> key,
    required BigInt session,
    required BigInt seq,
    required int dx,
    required int dy,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(key, serializer);
          sse_encode_u_64(session, serializer);
          sse_encode_u_64(seq, serializer);
          sse_encode_i_32(dx, serializer);
          sse_encode_i_32(dy, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBridgeSealScrollConstMeta,
        argValues: [key, session, seq, dx, dy],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeSealScrollConstMeta => const TaskConstMeta(
    debugName: "bridge_seal_scroll",
    argNames: ["key", "session", "seq", "dx", "dy"],
  );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  KeypairOut dco_decode_keypair_out(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return KeypairOut(
      privateKey: dco_decode_list_prim_u_8_strict(arr[0]),
      publicKey: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  OpenOut dco_decode_open_out(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return OpenOut(
      ok: dco_decode_bool(arr[0]),
      error: dco_decode_String(arr[1]),
      session: dco_decode_u_64(arr[2]),
      seq: dco_decode_u_64(arr[3]),
      msgType: dco_decode_u_8(arr[4]),
      a: dco_decode_i_64(arr[5]),
      b: dco_decode_i_64(arr[6]),
    );
  }

  @protected
  PairOut dco_decode_pair_out(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return PairOut(
      ok: dco_decode_bool(arr[0]),
      error: dco_decode_String(arr[1]),
      phoneKey: dco_decode_list_prim_u_8_strict(arr[2]),
      desktopKey: dco_decode_list_prim_u_8_strict(arr[3]),
      udpPort: dco_decode_u_16(arr[4]),
      sessionHint: dco_decode_u_64(arr[5]),
      serverName: dco_decode_String(arr[6]),
    );
  }

  @protected
  QrOut dco_decode_qr_out(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return QrOut(
      ok: dco_decode_bool(arr[0]),
      error: dco_decode_String(arr[1]),
      host: dco_decode_String(arr[2]),
      tcpPort: dco_decode_u_16(arr[3]),
      udpPort: dco_decode_u_16(arr[4]),
      serverFp: dco_decode_list_prim_u_8_strict(arr[5]),
      deviceName: dco_decode_String(arr[6]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  KeypairOut sse_decode_keypair_out(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_privateKey = sse_decode_list_prim_u_8_strict(deserializer);
    var var_publicKey = sse_decode_list_prim_u_8_strict(deserializer);
    return KeypairOut(privateKey: var_privateKey, publicKey: var_publicKey);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  OpenOut sse_decode_open_out(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ok = sse_decode_bool(deserializer);
    var var_error = sse_decode_String(deserializer);
    var var_session = sse_decode_u_64(deserializer);
    var var_seq = sse_decode_u_64(deserializer);
    var var_msgType = sse_decode_u_8(deserializer);
    var var_a = sse_decode_i_64(deserializer);
    var var_b = sse_decode_i_64(deserializer);
    return OpenOut(
      ok: var_ok,
      error: var_error,
      session: var_session,
      seq: var_seq,
      msgType: var_msgType,
      a: var_a,
      b: var_b,
    );
  }

  @protected
  PairOut sse_decode_pair_out(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ok = sse_decode_bool(deserializer);
    var var_error = sse_decode_String(deserializer);
    var var_phoneKey = sse_decode_list_prim_u_8_strict(deserializer);
    var var_desktopKey = sse_decode_list_prim_u_8_strict(deserializer);
    var var_udpPort = sse_decode_u_16(deserializer);
    var var_sessionHint = sse_decode_u_64(deserializer);
    var var_serverName = sse_decode_String(deserializer);
    return PairOut(
      ok: var_ok,
      error: var_error,
      phoneKey: var_phoneKey,
      desktopKey: var_desktopKey,
      udpPort: var_udpPort,
      sessionHint: var_sessionHint,
      serverName: var_serverName,
    );
  }

  @protected
  QrOut sse_decode_qr_out(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ok = sse_decode_bool(deserializer);
    var var_error = sse_decode_String(deserializer);
    var var_host = sse_decode_String(deserializer);
    var var_tcpPort = sse_decode_u_16(deserializer);
    var var_udpPort = sse_decode_u_16(deserializer);
    var var_serverFp = sse_decode_list_prim_u_8_strict(deserializer);
    var var_deviceName = sse_decode_String(deserializer);
    return QrOut(
      ok: var_ok,
      error: var_error,
      host: var_host,
      tcpPort: var_tcpPort,
      udpPort: var_udpPort,
      serverFp: var_serverFp,
      deviceName: var_deviceName,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_keypair_out(KeypairOut self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.privateKey, serializer);
    sse_encode_list_prim_u_8_strict(self.publicKey, serializer);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_open_out(OpenOut self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ok, serializer);
    sse_encode_String(self.error, serializer);
    sse_encode_u_64(self.session, serializer);
    sse_encode_u_64(self.seq, serializer);
    sse_encode_u_8(self.msgType, serializer);
    sse_encode_i_64(self.a, serializer);
    sse_encode_i_64(self.b, serializer);
  }

  @protected
  void sse_encode_pair_out(PairOut self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ok, serializer);
    sse_encode_String(self.error, serializer);
    sse_encode_list_prim_u_8_strict(self.phoneKey, serializer);
    sse_encode_list_prim_u_8_strict(self.desktopKey, serializer);
    sse_encode_u_16(self.udpPort, serializer);
    sse_encode_u_64(self.sessionHint, serializer);
    sse_encode_String(self.serverName, serializer);
  }

  @protected
  void sse_encode_qr_out(QrOut self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ok, serializer);
    sse_encode_String(self.error, serializer);
    sse_encode_String(self.host, serializer);
    sse_encode_u_16(self.tcpPort, serializer);
    sse_encode_u_16(self.udpPort, serializer);
    sse_encode_list_prim_u_8_strict(self.serverFp, serializer);
    sse_encode_String(self.deviceName, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
